#!/usr/bin/env bash

set_colors() {
	# settings colors
	if [ "$COLOR_SUPPORT" = true ]; then
		RED="!Y FG0xFFd30606 Y!"
		#FULL_RED="!Y bg0xFFd30606 u0xFF931501 Y!"
	else
		RED=""
	fi

}

# parsing command line arguments
while [[ $# -gt 0 ]]; do
key="$1"

case $key in
    -V|--verbose)
		VERBOSE=true
		shift # past argument
		;;
    -c|--color)
		COLOR_SUPPORT=true
		shift # past argument
		;;
    *)
		echo "ERROR: unknown option '$1'"
		exit -1
    ;;
esac
done

set_colors

# get data for current sink
DATA=$(pacmd list-sinks | grep -e "\\* index:" -A 15)
MUTED=$(echo $DATA | grep -E "muted:\\s+(yes|no)" -o | cut -d ':' -f 2 | xargs)
VOLUME=$(echo $DATA | cut -d '/' -f 2 | xargs)
COLOR=""

if [ "$MUTED" = "yes" ]; then
	VOLUME="muted"
	COLOR=$RED
else
	VOL_N=$(echo $VOLUME | cut -d '%' -f 1)
	VOLUME="VOL: $VOLUME"

	if [ "$VOL_N" -gt 100 ]; then
		COLOR=$RED
	fi
fi

echo "$COLOR$VOLUME"
