#!/bin/sh

alias\
	ls="ls --color=auto"\
	ll="ls -hl --color=auto"\
	la="ls -a --color=auto"\
	lla="ls -hla --color=auto"\
	grep="grep --color=auto"\
	cp="cp -v"\
	mv="mv -v"\
	rm="rm -v"\
	mkd="mkdir -pv"\
	dotfiles="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
