#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore

$HOME/.config/polybar/launch &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Emacs state=tiled
bspc rule -a TelegramDesktop state=floating
